name: CI-CD to Local VM

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/msa
            git pull
            chmod +x ./blue-green-deploy.sh
            ./blue-green-deploy.sh
            ./deploy.sh
          timeout: 60s
          command_timeout: 15m

