name: CI-CD to Local VM

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "SSH key file contents:"
          cat ~/.ssh/deploy_key
        env:
          SSH_KEY: ${{ secrets.VM_PRIVATE_KEY }}

      - name: Debug Connection
        run: |
          echo "Testing SSH connection..."
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -p 22 ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} 'echo "SSH connection successful"'

      - name: SSH into VM and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key_path: ~/.ssh/deploy_key
          port: 22
          script: |
            cd ~/msa
            git pull
            chmod +x ./blue-green-deploy.sh
            ./blue-green-deploy.sh
            ./deploy.sh
          timeout: 60s
          command_timeout: 15m

